# Generated by Django 5.0.6 on 2024-09-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='short_detail',
        ),
    ]
